### ISSUE TITLE
Where are all the pages?

### ISSUE THREAD

**Issue by brigleb** [needmore/thejobpdx#26]
You can't actually get to any interviews. What on earth is going on?

**Comment by gregorholtz** [comment]
@brigleb Which pages are experiencing these issues? I'm able to get to the interviews via the blocks at the bottom of the homepage and the archive button in the header...

**Comment by brigleb** [comment]
@gregorholtz ah well actually I fixed that last night by clearing the cache a few times, was very weird and I have no idea why it was happening but I'm glad you doble checked and we will just close this for now. Thanks!
